<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class Dashboard extends MY_Controller {
    function __construct() {
        parent::__construct();
		$this->load->model("Option_model");
    }

    public function index() {
		$schoolName = $this->Option_model->get_option(1)["VALUE"];
        if (is_teacher()) {
    		$data["typeid"] = "2";
    		$data["user"] = $this->Teacher_model->get_teacher($this->session->userid);
    		$data['type'] = "Enseignant du $schoolName";
    		$data["programs"] = $this->Teacher_model->get_teacher_programs($data["user"]["ID"]);
    		$data["students"] = $this->Student_model->get_all_students_by_teacher_id($data["user"]["ID"]);
    	}

    	if (is_employer()) {
    		$data["typeid"] = "3";
    		$data["user"] = $this->Employer_model->get_employer($this->session->userid);
    		$data['type'] = "Employeur pour $schoolName";
    	}

    	if (is_student()) {
    		$data["typeid"] = "1";
    		$data["user"] = $this->Student_model->get_student($this->session->userid);
    		$data['type'] = "Élève pour $schoolName";
    	}

        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
