<?php /*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Followup extends MY_Controller {
	function __construct() {
		parent::__construct();
		$this->load->model('Followup_model');
	}

	/*
	 * Listing of followups
	 */
	function index() {
		$data['followups'] = $this->Followup_model->get_all_followups();

		$data['_view'] = 'followup/index';
		$this->load->view('layouts/main', $data);
	}

	/*
	 * Adding a new followup
	 */
	function add() {
		$this->load->library('form_validation');

		$this->form_validation->set_rules('CREATOR_ID', 'CREATOR ID', 'integer');

		if ($this->form_validation->run()) {
			$params = array(
				'INTERNSHIP_ID' => $this->input->post('INTERNSHIP_ID'),
				'CREATOR_ID' => $this->input->post('CREATOR_ID'),
				'CREATOR_TYPE' => $this->input->post('CREATOR_TYPE'),
				'DESCRIPTION' => $this->input->post('DESCRIPTION'),
			);

			$followup_id = $this->Followup_model->add_followup($params);
			redirect('followup/index');
		} else {
			$this->load->model('Internship_model');
			$data['all_internships'] = $this->Internship_model->get_all_internships();

			$this->load->model('Creator_type_model');
			$data['all_creator_types'] = $this->Creator_type_model->get_all_creator_types();

			$data['_view'] = 'followup/add';
			$this->load->view('layouts/main', $data);
		}
	}

	/*
	 * Editing a followup
	 */
	function edit($ID) {
		// check if the followup exists before trying to edit it
		$data['followup'] = $this->Followup_model->get_followup($ID);

		if (isset($data['followup']['ID'])) {
			$this->load->library('form_validation');

			$this->form_validation->set_rules('CREATOR_ID', 'CREATOR ID', 'integer');

			if ($this->form_validation->run()) {
				$params = array(
					'INTERNSHIP_ID' => $this->input->post('INTERNSHIP_ID'),
					'CREATOR_ID' => $this->input->post('CREATOR_ID'),
					'CREATOR_TYPE' => $this->input->post('CREATOR_TYPE'),
					'DESCRIPTION' => $this->input->post('DESCRIPTION'),
				);

				$this->Followup_model->update_followup($ID, $params);
				redirect('followup/index');
			} else {
				$this->load->model('Internship_model');
				$data['all_internships'] = $this->Internship_model->get_all_internships();

				$this->load->model('Creator_type_model');
				$data['all_creator_types'] = $this->Creator_type_model->get_all_creator_types();

				$data['_view'] = 'followup/edit';
				$this->load->view('layouts/main', $data);
			}
		} else {
			show_error('The followup you are trying to edit does not exist.');
		}
	}

	/*
	 * Deleting followup
	 */
	function remove($ID) {
		$followup = $this->Followup_model->get_followup($ID);

		// check if the followup exists before trying to delete it
		if (isset($followup['ID'])) {
			$this->Followup_model->delete_followup($ID);
			redirect('followup/index');
		} else {
			show_error('The followup you are trying to delete does not exist.');
		}
	}
}
