<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Log extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Log_model');
    } 

    /*
     * Listing of logs
     */
    function index()
    {
        $data['logs'] = $this->Log_model->get_all_logs();
        
        $data['_view'] = 'log/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new log
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'INTERNSHIP_ID' => $this->input->post('INTERNSHIP_ID'),
				'DATE' => $this->input->post('DATE'),
				'DESCRIPTION' => $this->input->post('DESCRIPTION'),
            );
            
            $log_id = $this->Log_model->add_log($params);
            redirect('log/index');
        }
        else
        {
			$this->load->model('Internship_model');
			$data['all_internships'] = $this->Internship_model->get_all_internships();
            
            $data['_view'] = 'log/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a log
     */
    function edit($ID)
    {   
        // check if the log exists before trying to edit it
        $data['log'] = $this->Log_model->get_log($ID);
        
        if(isset($data['log']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'INTERNSHIP_ID' => $this->input->post('INTERNSHIP_ID'),
					'DATE' => $this->input->post('DATE'),
					'DESCRIPTION' => $this->input->post('DESCRIPTION'),
                );

                $this->Log_model->update_log($ID,$params);            
                redirect('log/index');
            }
            else
            {
				$this->load->model('Internship_model');
				$data['all_internships'] = $this->Internship_model->get_all_internships();

                $data['_view'] = 'log/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The log you are trying to edit does not exist.');
    } 

    /*
     * Deleting log
     */
    function remove($ID)
    {
        $log = $this->Log_model->get_log($ID);

        // check if the log exists before trying to delete it
        if(isset($log['ID']))
        {
            $this->Log_model->delete_log($ID);
            redirect('log/index');
        }
        else
            show_error('The log you are trying to delete does not exist.');
    }
    
}
