<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Message extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Message_model');
    } 

    /*
     * Listing of messages
     */
    function index()
    {
        $data['messages'] = $this->Message_model->get_all_messages();
        
        $data['_view'] = 'message/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new message
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'INTERNSHIP_ID' => $this->input->post('INTERNSHIP_ID'),
				'TO_TYPE' => $this->input->post('TO_TYPE'),
				'FROM_TYPE' => $this->input->post('FROM_TYPE'),
				'TO_ID' => $this->input->post('TO_ID'),
				'FROM_ID' => $this->input->post('FROM_ID'),
				'DESCRIPTION' => $this->input->post('DESCRIPTION'),
            );
            
            $message_id = $this->Message_model->add_message($params);
            redirect('message/index');
        }
        else
        {
			$this->load->model('Internship_model');
			$data['all_internships'] = $this->Internship_model->get_all_internships();

			$this->load->model('Creator_type_model');
			$data['all_creator_types'] = $this->Creator_type_model->get_all_creator_types();
			$data['all_creator_types'] = $this->Creator_type_model->get_all_creator_types();
            
            $data['_view'] = 'message/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a message
     */
    function edit($ID)
    {   
        // check if the message exists before trying to edit it
        $data['message'] = $this->Message_model->get_message($ID);
        
        if(isset($data['message']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'INTERNSHIP_ID' => $this->input->post('INTERNSHIP_ID'),
					'TO_TYPE' => $this->input->post('TO_TYPE'),
					'FROM_TYPE' => $this->input->post('FROM_TYPE'),
					'TO_ID' => $this->input->post('TO_ID'),
					'FROM_ID' => $this->input->post('FROM_ID'),
					'DESCRIPTION' => $this->input->post('DESCRIPTION'),
                );

                $this->Message_model->update_message($ID,$params);            
                redirect('message/index');
            }
            else
            {
				$this->load->model('Internship_model');
				$data['all_internships'] = $this->Internship_model->get_all_internships();

				$this->load->model('Creator_type_model');
				$data['all_creator_types'] = $this->Creator_type_model->get_all_creator_types();
				$data['all_creator_types'] = $this->Creator_type_model->get_all_creator_types();

                $data['_view'] = 'message/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The message you are trying to edit does not exist.');
    } 

    /*
     * Deleting message
     */
    function remove($ID)
    {
        $message = $this->Message_model->get_message($ID);

        // check if the message exists before trying to delete it
        if(isset($message['ID']))
        {
            $this->Message_model->delete_message($ID);
            redirect('message/index');
        }
        else
            show_error('The message you are trying to delete does not exist.');
    }
    
    function view()
    {
        $data['messages'] = $this->Message_model->get_all_messages_for_user($this->session->userid, $this->session->status);
        $data['_view'] = 'message/view';
        $this->load->view('layouts/main',$data);        
    }
    
}
