<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Obligation extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Obligation_model');
    } 

    /*
     * Listing of obligations
     */
    function index()
    {
        $data['obligations'] = $this->Obligation_model->get_all_obligations();
        
        $data['_view'] = 'obligation/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new obligation
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'INTERNSHIP_ID' => $this->input->post('INTERNSHIP_ID'),
				'DOCUMENT_ID' => $this->input->post('DOCUMENT_ID'),
				'DATE' => $this->input->post('DATE'),
            );
            
            $obligation_id = $this->Obligation_model->add_obligation($params);
            redirect('obligation/index');
        }
        else
        {
			$this->load->model('Internship_model');
			$data['all_internships'] = $this->Internship_model->get_all_internships();

			$this->load->model('Document_model');
			$data['all_documents'] = $this->Document_model->get_all_documents();
            
            $data['_view'] = 'obligation/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a obligation
     */
    function edit($ID)
    {   
        // check if the obligation exists before trying to edit it
        $data['obligation'] = $this->Obligation_model->get_obligation($ID);
        
        if(isset($data['obligation']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'INTERNSHIP_ID' => $this->input->post('INTERNSHIP_ID'),
					'DOCUMENT_ID' => $this->input->post('DOCUMENT_ID'),
					'DATE' => $this->input->post('DATE'),
                );

                $this->Obligation_model->update_obligation($ID,$params);            
                redirect('obligation/index');
            }
            else
            {
				$this->load->model('Internship_model');
				$data['all_internships'] = $this->Internship_model->get_all_internships();

				$this->load->model('Document_model');
				$data['all_documents'] = $this->Document_model->get_all_documents();

                $data['_view'] = 'obligation/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The obligation you are trying to edit does not exist.');
    } 

    /*
     * Deleting obligation
     */
    function remove($ID)
    {
        $obligation = $this->Obligation_model->get_obligation($ID);

        // check if the obligation exists before trying to delete it
        if(isset($obligation['ID']))
        {
            $this->Obligation_model->delete_obligation($ID);
            redirect('obligation/index');
        }
        else
            show_error('The obligation you are trying to delete does not exist.');
    }
    
}
