<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class Option extends MY_Controller {
    function __construct() {
        parent::__construct();
        $this->load->model('Option_model');
    }

    /*
     * Listing of options
     */
    function index() {
        $data['options'] = $this->Option_model->get_all_options();

        $data['_view'] = 'option/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new option
     */
    function add() {
        if(isset($_POST) && count($_POST) > 0) {
            $params = array(
				'NAME'  => $this->input->post('NAME'),
				'VALUE' => $this->input->post('VALUE'),
            );

            $option_id = $this->Option_model->add_option($params);
            redirect('option/index');
        } else {
            $data['_view'] = 'option/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a option
     */
    function edit($ID) {
        // check if the option exists before trying to edit it
        $data['option'] = $this->Option_model->get_option($ID);

        if(isset($data['option']['ID'])) {
            if(isset($_POST) && count($_POST) > 0) {
                $params = array(
					'NAME' => $this->input->post('NAME'),
					'VALUE' => $this->input->post('VALUE'),
                );

                $this->Option_model->update_option($ID,$params);
                redirect('option/index');
            } else {
                $data['_view'] = 'option/edit';
                $this->load->view('layouts/main',$data);
            }
        } else {
            show_error('The option you are trying to edit does not exist.');
        }
    }

    /*
     * Deleting option
     */
    function remove($ID) {
        $option = $this->Option_model->get_option($ID);

        // check if the option exists before trying to delete it
        if(isset($option['ID'])) {
            $this->Option_model->delete_option($ID);
            redirect('option/index');
        } else {
            show_error('The option you are trying to delete does not exist.');
        }
    }
}
