<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Absence_model extends CI_Model {
	function __construct() {
		parent::__construct();
	}

	/*
	 * Get absence by ID
	 */
	function get_absence($ID) {
		return $this->db->get_where('ABSENCES', array('ID' => $ID))->row_array();
	}

	/*
	 * Get all absences
	 */
	function get_all_absences() {
		$this->db->order_by('FORDATE', 'asc');
		return $this->db->get('ABSENCES')->result_array();
	}

	function get_all_absences_filter($studentid, $start, $end) {

		$this->db->join('INTERNSHIPS', 'INTERNSHIPS.ID = ABSENCES.INTERNSHIP_ID');

		if ($studentid != "null") {
			$this->db->where('INTERNSHIPS.STUDENT_ID', $studentid);
		}

		if ($start != "null") {
			$this->db->where('ABSENCES.FORDATE >=', $start);
		}

		if ($end != "null") {
			$this->db->where('ABSENCES.FORDATE <=', $end);
		}

		$this->db->order_by('FORDATE', 'asc');
		return $this->db->get('ABSENCES')->result_array();
	}

	/*
	 * Get all absences
	 */
	function get_all_absences_where($params) {
		return $this->db->get_where('ABSENCES', $params)->result_array();
	}

	/*
	 * function to add new absence
	 */
	function add_absence($params) {
		$this->db->insert('ABSENCES', $params);
		return $this->db->insert_id();
	}

	/*
	 * function to update absence
	 */
	function update_absence($ID, $params) {
		$this->db->where('ID', $ID);
		return $this->db->update('ABSENCES', $params);
	}

	/*
	 * function to delete absence
	 */
	function delete_absence($ID) {
		return $this->db->delete('ABSENCES', array('ID' => $ID));
	}
}
