<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Creator_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    
    

    
    /*
     * Get creator_type by ID
     */
    function get_creator_type($ID)
    {
        return $this->db->get_where('CREATOR_TYPES',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all creator_types
     */
    function get_all_creator_types()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('CREATOR_TYPES')->result_array();
    }
        
    /*
     * function to add new creator_type
     */
    function add_creator_type($params)
    {
        $this->db->insert('CREATOR_TYPES',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update creator_type
     */
    function update_creator_type($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('CREATOR_TYPES',$params);
    }
    
    /*
     * function to delete creator_type
     */
    function delete_creator_type($ID)
    {
        return $this->db->delete('CREATOR_TYPES',array('ID'=>$ID));
    }
}
