<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cron_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
		$this->load->model("Student_model");
		$this->load->model("Teacher_model");
		$this->load->model("Program_model");
    }

	public function add_new_teacher($params)
	{
        $this->db->insert('TEACHERS',$params);
        return $this->db->insert_id();			
	}

	public function add_new_student($params)
	{
        $this->db->insert('STUDENTS',$params);
        return $this->db->insert_id();		
	}
	
	public function add_new_program($params)
	{
        $this->db->insert('PROGRAMS',$params);
        return $this->db->insert_id();		
	}

	public function get_db_teachers()
	{
		return $this->Teacher_model->get_all_teachers();
	}

	public function get_db_students()
	{
		return $this->Student_model->get_all_students();
	}

	public function get_db_programs()
	{
		return $this->Program_model->get_all_programs();
	}
	
	public function get_corresponding_program_id_by_name($name)
	{
		return $this->db->get_where('PROGRAMS', array('NAME' => $name))->row();
	}
	
}