<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Employer_program_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get block by ID
     */
   
    function is_in_database($employer_id, $program_id)
    {
        $this->db->from('EMPLOYER_PROGRAMS AS EMP_PRO');
        $this->db->where('EMP_PRO.EMPLOYER_ID',$employer_id);
        $this->db->where('EMP_PRO.PROGRAM_ID',$program_id);
        $query = $this->db->get();
        
        if ($query->num_rows() > 0){
            return true;
        }
        else{
            return false;
        }
    }
    
    function add_employer_program($params)
    {
        $this->db->insert('EMPLOYER_PROGRAMS',$params);
        return $this->db->insert_id();
    }
    
    function delete_employer_from_program($employer_id, $program_id)
    {
        return $this->db->delete('EMPLOYER_PROGRAMS', array('EMPLOYER_ID' => $employer_id, 'PROGRAM_ID' => $program_id));
    }

}
