<?php /*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Followup_model extends CI_Model {
	function __construct() {
		parent::__construct();
	}

	/*
	 * Get followup by ID
	 */
	function get_followup($ID) {
		return $this->db->get_where('FOLLOWUPS', array('ID' => $ID))->row_array();
	}

	/*
	 * Get all followups
	 */
	function get_all_followups() {
		$this->db->order_by('ID', 'desc');
		return $this->db->get('FOLLOWUPS')->result_array();
	}

	/*
	 * function to add new followup
	 */
	function add_followup($params) {
		$this->db->insert('FOLLOWUPS', $params);
		return $this->db->insert_id();
	}

	/*
	 * function to update followup
	 */
	function update_followup($ID, $params) {
		$this->db->where('ID', $ID);
		return $this->db->update('FOLLOWUPS', $params);
	}

	/*
	 * function to delete followup
	 */
	function delete_followup($ID) {
		return $this->db->delete('FOLLOWUPS', array('ID' => $ID));
	}
}
