<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Form_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get form by ID
     */
    function get_form($ID)
    {
        return $this->db->get_where('FORMS',array('ID'=>$ID))->row_array();
    }



    /*
     * Get all forms
     */
    function get_all_forms()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('FORMS')->result_array();
    }
       

      function get_all_forms_where($params)
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get_where('FORMS',$params)->result_array();
    }     

       
        
    /*
     * function to add new form
     */
    function add_form($params)
    {
        $this->db->insert('FORMS',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update form
     */
    function update_form($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('FORMS',$params);
    }
    
    /*
     * function to delete form
     */
    function delete_form($ID)
    {
        return $this->db->delete('FORMS',array('ID'=>$ID));
    }
    

}