<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class Option_model extends CI_Model {
    function __construct() {
        parent::__construct();
    }

    /*
     * Get option by ID
     */
    function get_option($ID) {
        return $this->db->get_where('OPTIONS', array('ID' => $ID))->row_array();
    }

    function get_option_by_name($name) {
        return $this->db->get_where("OPTIONS", array("NAME" => $name))->row_array();
    }

    /*
     * Get all options
     */
    function get_all_options() {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('OPTIONS')->result_array();
    }

    /*
     * function to add new option
     */
    function add_option($params) {
        $this->db->insert('OPTIONS', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update option
     */
    function update_option($ID, $params) {
        $this->db->where('ID', $ID);
        return $this->db->update('OPTIONS', $params);
    }

    /*
     * function to delete option
     */
    function delete_option($ID) {
        return $this->db->delete('OPTIONS', array('ID' => $ID));
    }
}
