<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Program_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get program by ID
     */
    function get_program($ID)
    {
        return $this->db->get_where('PROGRAMS',array('ID'=>$ID))->row_array();
    }

    /*
     * Get all programs
     */
    function get_all_programs()
    {
        $this->db->order_by('NAME', 'asc');
        return $this->db->get('PROGRAMS')->result_array();
    }

    /*
     * function to add new program
     */
    function add_program($params)
    {
        $this->db->insert('PROGRAMS',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update program
     */
    function update_program($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('PROGRAMS',$params);
    }

    /*
     * function to delete program
     */
    function delete_program($ID)
    {
        return $this->db->delete('PROGRAMS',array('ID'=>$ID));
    }

    function get_program_name_by_id($ID)
    {
        return $this->db->get_where('PROGRAMS',array('ID' => $ID))->row_array();
    }
}
