<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Setting_model extends CI_Model {
	function __construct() {
		parent::__construct();
	}

	/*
	 * Get block by settings
	 */
	function get_setting($NAME) {
		return $this->db->get_where('SETTINGS', array('NAME' => $NAME))->row()->VALUE;
	}

	/*
	 * Get all settings
	 */
	function get_all_settings($params) {
		$this->db->order_by('ID', 'asc');
		return $this->db->get('SETTINGS')->result_array();
	}

	/*
	 * Get all settings
	 */
	function get_all_settings_where($params) {
		$this->db->order_by('ID', 'asc');
		return $this->db->get_where('SETTINGS', $params)->result_array();
	}

	/*
	 * function to add new setting
	 */
	function add_setting($params) {
		$this->db->insert('SETTINGS', $params);
		return $this->db->insert_id();
	}

	/*
	 * function to update setting
	 */
	function update_setting($ID, $params) {
		$this->db->where('ID', $ID);
		return $this->db->update('SETTINGS', $params);
	}

	/*
	 * function to delete setting
	 */
	function delete_setting($ID) {
		return $this->db->delete('SETTINGS', array('ID' => $ID));
	}
}
