<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class User_model extends CI_Model {
    function __construct() {
        parent::__construct();
    }

    /*
     * Get user by ID
     */
    function get_admin($ID) {
        return $this->db->get_where('ADMINISTRATORS', array('ID' => $ID))->row_array();
    }

    /*
     * Get all users
     */
    function get_all_admins() {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('ADMINISTRATORS')->result_array();
    }

    /*
     * function to add new user
     */
    function add_admin($params) {
        $this->db->insert('ADMINISTRATORS', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update user
     */
    function update_admin($ID, $params) {
        $this->db->where('ID', $ID);
        return $this->db->update('ADMINISTRATORS', $params);
    }

    /*
     * function to delete user
     */
    function delete_admin($ID) {
        return $this->db->delete('ADMINISTRATORS', array('ID' => $ID));
    }

    function get_admin_by_email($email) {
        return $this->db->get_where("ADMINISTRATORS", array("EMAIL" => $email))->row_array();
    }

    function user_auth($username, $password, $type) {
        if($type == "employer") {
            //$username = intval($username);
            $username = preg_replace('/\D/', '', $username);
            $this->db->where("PHONEHASH", $username);
        } else {
            $this->db->where("USERNAME", $username);
        }

        if ($type == "admin") {
            $result = $this->db->get('USERS')->row_array();
        } else if ($type == "employer") {
            $result = $this->db->get('EMPLOYERS')->row_array();
        }

        if ($result) {
            if (password_verify($password, $result['PASSWORD'])) {
                return $result;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
}
